// Datos de barrios/sectores para rutas de AMARED.
// Fuente base: Plano U15 Barrios - Alcaldía de Ibagué / Secretaría de Planeación Municipal.
// Esta lista se usa como apoyo para autocompletar el barrio en pedidos y sugerir rutas en envíos.
(function(){
  const AMARED_IBAGUE_NEIGHBORHOODS = [
  {name:"Edificio Kiwana", aliases:["Kiwana", "Edificio Kiwana", "Calle 53", "Cl. 53", "Calle 53 #6A-21"], route:"occidente", score:1},
  {name:"Augusto e Medina", route:"por_asignar", score:50},
  {name:"20 de Julio", route:"occidente", score:5},
  {name:"Antonio Nariño", route:"por_asignar", score:50},
  {name:"Alfonso Lopez", route:"occidente", score:5},
  {name:"4 Etapa del Jordán", route:"oriente", score:6},
  {name:"Agua Viva", route:"por_asignar", score:50},
  {name:"Portal del Vergel", route:"oriente", score:6},
  {name:"Alamos", route:"por_asignar", score:50},
  {name:"Urb. los Lagos", aliases:["los Lagos"], route:"oriente", score:6},
  {name:"Baltazar", route:"occidente", score:5},
  {name:"7 de Agosto", route:"occidente", score:5},
  {name:"Belalcazar", route:"por_asignar", score:50},
  {name:"Calarca", route:"occidente", score:5},
  {name:"6 Etapa del Jordán", route:"oriente", score:6},
  {name:"Altos de San Francisco", route:"oriente", score:6},
  {name:"Primavera de Entre Rios", route:"por_asignar", score:50},
  {name:"Chico", route:"por_asignar", score:50},
  {name:"Urb. Monte Carlos II", aliases:["Monte Carlos II"], route:"oriente", score:6},
  {name:"Centro", aliases:["Centro de Ibagué", "Centro Ibague"], route:"occidente", score:5},
  {name:"Alaska", route:"occidente", score:5},
  {name:"Calambeo", route:"occidente", score:5},
  {name:"Cambulos", route:"occidente", score:5},
  {name:"7 Etapa del Jordán", route:"oriente", score:6},
  {name:"Balcones del Vergel", route:"oriente", score:6},
  {name:"Reservas del Pedregal", route:"oriente", score:6},
  {name:"El Salado", aliases:["Salado", "Especial El Salado", "La Ceiba", "Aeropuerto", "Aeropuerto Perales", "Comfatolima Lagos Club"], route:"oriente", score:10},
  {name:"Urb. Oviedo", aliases:["Oviedo"], route:"oriente", score:6},
  {name:"Combeima", route:"occidente", score:5},
  {name:"Ancon", route:"occidente", score:5},
  {name:"Carmenza Rocha", route:"occidente", score:5},
  {name:"Caracoli", route:"occidente", score:5},
  {name:"8 Etapa del Jordán", route:"oriente", score:6},
  {name:"Bosques del Vergel", route:"oriente", score:6},
  {name:"Rincon de San Francisco", route:"oriente", score:6},
  {name:"Hacienda el Recreo", route:"por_asignar", score:50},
  {name:"Urb. Pacande", aliases:["Pacande"], route:"oriente", score:6},
  {name:"Estacion", route:"occidente", score:5},
  {name:"Belen", route:"occidente", score:5},
  {name:"El Carmen", route:"occidente", score:5},
  {name:"Castilla", route:"occidente", score:5},
  {name:"9 Etapa del Jordán", route:"oriente", score:6},
  {name:"Brisas del Pedregal", route:"oriente", score:6},
  {name:"Rincon del Pedregal I", route:"oriente", score:6},
  {name:"Los Musicos", route:"por_asignar", score:50},
  {name:"Urb. Palma del Rio", aliases:["Palma del Rio"], route:"oriente", score:6},
  {name:"Interlaken", route:"occidente", score:5},
  {name:"Belencito", route:"occidente", score:5},
  {name:"Fenalco", route:"occidente", score:5},
  {name:"Gaitan", route:"occidente", score:5},
  {name:"Andalucia", route:"por_asignar", score:50},
  {name:"Cañaveral I", route:"oriente", score:6},
  {name:"Rincon del Pedregal II", route:"oriente", score:6},
  {name:"Mirador de Cantabria", route:"oriente", score:6},
  {name:"Urb. Palo Grande", aliases:["Palo Grande"], route:"oriente", score:6},
  {name:"La Pola", route:"occidente", score:5},
  {name:"Gaitan Parte Alta", route:"occidente", score:5},
  {name:"Jakaranda", route:"occidente", score:5},
  {name:"Arboleda Margaritas", route:"por_asignar", score:50},
  {name:"Cañaveral II", route:"oriente", score:6},
  {name:"Rincon del Vergel", route:"oriente", score:6},
  {name:"Modelia I", route:"oriente", score:6},
  {name:"Urb. Portales del Norte", aliases:["Portales del Norte"], route:"oriente", score:6},
  {name:"Libertador", route:"occidente", score:5},
  {name:"Centenario", route:"occidente", score:5},
  {name:"Inem", route:"occidente", score:5},
  {name:"Jesus Maria Cordoba", route:"por_asignar", score:50},
  {name:"Arkacentro", route:"oriente", score:6},
  {name:"Caminos de Juan Pablo II", route:"por_asignar", score:50},
  {name:"San Antonio", route:"por_asignar", score:50},
  {name:"Modelia II", route:"oriente", score:6},
  {name:"Urb. Praderas del Norte", aliases:["Praderas del Norte"], route:"oriente", score:6},
  {name:"Pola Parte Alta", route:"occidente", score:5},
  {name:"Cerro Pan de Azucar", route:"por_asignar", score:50},
  {name:"La Esperanza", route:"occidente", score:5},
  {name:"Jose Maria Cordoba Parte Baja", route:"por_asignar", score:50},
  {name:"Arkamonica", route:"oriente", score:6},
  {name:"Caminos de San Francisco", route:"oriente", score:6},
  {name:"Tierra Linda del Vergel", route:"oriente", score:6},
  {name:"Nueva Bilbao", route:"por_asignar", score:50},
  {name:"Urb. Reservas de Cantabria", aliases:["Reservas de Cantabria"], route:"oriente", score:6},
  {name:"Pueblo Nuevo", route:"occidente", score:5},
  {name:"Clarita Botero", route:"por_asignar", score:50},
  {name:"La Granja", route:"occidente", score:5},
  {name:"Limonar", route:"occidente", score:5},
  {name:"Arrayanes", route:"por_asignar", score:50},
  {name:"Caminos del Vergel", route:"oriente", score:6},
  {name:"Torre Fuente de los Rosales", route:"oriente", score:6},
  {name:"Pedro Ignacio Villamarin", route:"por_asignar", score:50},
  {name:"Urb. San Luis", aliases:["San Luis"], route:"oriente", score:6},
  {name:"San Pedro Alejandrino", route:"occidente", score:5},
  {name:"La Aurora", route:"occidente", score:5},
  {name:"Las Acacias", route:"por_asignar", score:50},
  {name:"Limonar V Sector", route:"occidente", score:5},
  {name:"Calatayud", route:"por_asignar", score:50},
  {name:"Condominio Ronda del Vergel", aliases:["Ronda del Vergel"], route:"oriente", score:6},
  {name:"Torres de la Calleja", route:"por_asignar", score:50},
  {name:"Rosales de Tailandia", route:"por_asignar", score:50},
  {name:"Urb. San Luis Gonzaga", aliases:["San Luis Gonzaga"], route:"oriente", score:6},
  {name:"La Paz", route:"occidente", score:5},
  {name:"San Simon Parte Alta", route:"occidente", score:5},
  {name:"Onzaga", route:"occidente", score:5},
  {name:"Conjunto Residencial la Alameda", aliases:["la Alameda"], route:"por_asignar", score:50},
  {name:"Condominio Tierra Alta", aliases:["Tierra Alta"], route:"por_asignar", score:50},
  {name:"Urb. Arkala I", aliases:["Arkala I"], route:"oriente", score:6},
  {name:"Santa Ana", route:"por_asignar", score:50},
  {name:"La Sofia", route:"occidente", score:5},
  {name:"San Simon Parte Baja", route:"occidente", score:5},
  {name:"Piedra Pintada", aliases:["Piedrapintada", "Piedra Pintada Alta", "Piedra Pintada Baja"], route:"oriente", score:6},
  {name:"Cordobita", route:"por_asignar", score:50},
  {name:"Conjunto Cerrado Ambala", route:"oriente", score:6},
  {name:"Urb. Arkambuco I", aliases:["Arkambuco I"], route:"oriente", score:6},
  {name:"Sector los Alpes", aliases:["los Alpes"], route:"por_asignar", score:50},
  {name:"Urb. San Pablo", aliases:["San Pablo"], route:"oriente", score:6},
  {name:"La Trinidad", route:"occidente", score:5},
  {name:"Villa Ilusion", route:"por_asignar", score:50},
  {name:"Pijao", route:"occidente", score:5},
  {name:"El Eden", route:"por_asignar", score:50},
  {name:"Conjunto Cerrado los Balsos", route:"por_asignar", score:50},
  {name:"Urb. Colinas del Norte", aliases:["Colinas del Norte"], route:"occidente", score:10},
  {name:"Timaka", route:"por_asignar", score:50},
  {name:"Urb. San Sebastian", aliases:["San Sebastian"], route:"oriente", score:6},
  {name:"Malavar", route:"occidente", score:5},
  {name:"Villa Pinzon", route:"occidente", score:5},
  {name:"Restrepo", route:"occidente", score:5},
  {name:"La Campiña", route:"oriente", score:6},
  {name:"El Mirador", route:"por_asignar", score:50},
  {name:"Urb. Pedregal", aliases:["Pedregal"], route:"oriente", score:6},
  {name:"Urb. Santa Coloma", aliases:["Santa Coloma"], route:"por_asignar", score:50},
  {name:"Urb. Santa Catalina I", aliases:["Santa Catalina I"], route:"oriente", score:6},
  {name:"Paraiso", route:"occidente", score:5},
  {name:"Villa Valentina", route:"occidente", score:5},
  {name:"Rincon Piedra Pintada", route:"oriente", score:6},
  {name:"La Ladera", route:"por_asignar", score:50},
  {name:"El Triunfo", route:"occidente", score:5},
  {name:"Urb. Villa Patricia", aliases:["Villa Patricia"], route:"por_asignar", score:50},
  {name:"Urb. Alameda", aliases:["Alameda"], route:"por_asignar", score:50},
  {name:"Urb. Santa Monica", aliases:["Santa Monica"], route:"oriente", score:6},
  {name:"San Diego", route:"occidente", score:5},
  {name:"Viveros", route:"occidente", score:5},
  {name:"San Carlos", route:"occidente", score:5},
  {name:"Las Margaritas", route:"por_asignar", score:50},
  {name:"Estancia del Vergel", route:"oriente", score:6},
  {name:"Urb. Altos de Ambala", aliases:["Altos de Ambala"], route:"oriente", score:6},
  {name:"Urb. Alberto Lleras C.", aliases:["Alberto Lleras C."], route:"por_asignar", score:50},
  {name:"Urb. Shaddi", aliases:["Shaddi"], route:"oriente", score:6},
  {name:"Santa Barbara", route:"occidente", score:5},
  {name:"San Luis", route:"oriente", score:6},
  {name:"Las Orquideas", route:"por_asignar", score:50},
  {name:"Fuente de los Rosales", route:"oriente", score:6},
  {name:"Urb. Altos del Pedregal", aliases:["Altos del Pedregal"], route:"oriente", score:6},
  {name:"Urb. Ambikaima", aliases:["Ambikaima"], route:"por_asignar", score:50},
  {name:"Urb. Territorio de Paz", aliases:["Territorio de Paz"], route:"oriente", score:6},
  {name:"Santa Cruz", route:"occidente", score:5},
  {name:"Sorrento", route:"occidente", score:5},
  {name:"Macadamia", route:"por_asignar", score:50},
  {name:"Fuente de los Rosales II", route:"oriente", score:6},
  {name:"Urb. Ambala", aliases:["Ambala"], route:"oriente", score:6},
  {name:"Urb. Cantabria", aliases:["Cantabria"], route:"oriente", score:6},
  {name:"Urb. Tierra Firme", aliases:["Tierra Firme"], route:"oriente", score:6},
  {name:"VI Brigada", route:"por_asignar", score:50},
  {name:"Toscana", route:"por_asignar", score:50},
  {name:"Multifamiliares el Jordán", route:"oriente", score:6},
  {name:"La Balsa", route:"por_asignar", score:50},
  {name:"Urb. Antares I", aliases:["Antares I"], route:"por_asignar", score:50},
  {name:"Urb. Comfatolima", aliases:["Comfatolima"], route:"por_asignar", score:50},
  {name:"Urb. Villa Brasilia", aliases:["Villa Brasilia"], route:"oriente", score:6},
  {name:"Viña de Calambeo", route:"occidente", score:5},
  {name:"Triunfo", route:"occidente", score:5},
  {name:"Multifamiliares las Margaritas", route:"por_asignar", score:50},
  {name:"Urb. Antares II", aliases:["Antares II"], route:"por_asignar", score:50},
  {name:"Urb. Diana Milaidy", aliases:["Diana Milaidy"], route:"por_asignar", score:50},
  {name:"Urb. Villa Camila", aliases:["Villa Camila"], route:"oriente", score:6},
  {name:"Villa Adriana", route:"por_asignar", score:50},
  {name:"Villa Marle II", route:"por_asignar", score:50},
  {name:"Prados del Norte", route:"oriente", score:6},
  {name:"La Gaviota", route:"por_asignar", score:50},
  {name:"Urb. Arkala II", aliases:["Arkala II"], route:"oriente", score:6},
  {name:"Urb. el Dorado", aliases:["el Dorado"], route:"por_asignar", score:50},
  {name:"Urb. Villa Cindy", aliases:["Villa Cindy"], route:"oriente", score:6},
  {name:"Villa Marlen I", route:"por_asignar", score:50},
  {name:"Rincon de la Campiña", route:"oriente", score:6},
  {name:"Las Delicias", route:"por_asignar", score:50},
  {name:"Urb. Chicala", aliases:["Chicala"], route:"por_asignar", score:50},
  {name:"Urb. el Limon", aliases:["el Limon"], route:"por_asignar", score:50},
  {name:"Urb. Villa Clara I", aliases:["Villa Clara I"], route:"oriente", score:6},
  {name:"Villa Tereza", route:"por_asignar", score:50},
  {name:"San Jacinto", route:"por_asignar", score:50},
  {name:"Los Alpes", route:"por_asignar", score:50},
  {name:"Urb. Entre Rios", aliases:["Entre Rios"], route:"por_asignar", score:50},
  {name:"Urb. el Palmar", aliases:["el Palmar"], route:"oriente", score:6},
  {name:"Urb. Villa Clara II", aliases:["Villa Clara II"], route:"oriente", score:6},
  {name:"Torre Ladera", route:"por_asignar", score:50},
  {name:"Los Angeles", route:"por_asignar", score:50},
  {name:"Urb. Entre Rios II", aliases:["Entre Rios II"], route:"por_asignar", score:50},
  {name:"Urb. Fuente del Salado", aliases:["Fuente del Salado"], route:"oriente", score:10},
  {name:"Urb. Villa Julieta", aliases:["Villa Julieta"], route:"oriente", score:6},
  {name:"Urb. Aimara I", aliases:["Aimara I"], route:"por_asignar", score:50},
  {name:"Los Ciruelos", route:"por_asignar", score:50},
  {name:"Urb. Fuente de los Rosale I", aliases:["Fuente de los Rosale I"], route:"por_asignar", score:50},
  {name:"Urb. Fuente Santa", aliases:["Fuente Santa"], route:"por_asignar", score:50},
  {name:"Urb. Villa Rocio", aliases:["Villa Rocio"], route:"oriente", score:6},
  {name:"Urb. Aimara II", aliases:["Aimara II"], route:"por_asignar", score:50},
  {name:"Los Mandarinos", route:"por_asignar", score:50},
  {name:"Urb. Girasol", aliases:["Girasol"], route:"por_asignar", score:50},
  {name:"Urb. la Cabaña", aliases:["la Cabaña"], route:"por_asignar", score:50},
  {name:"Urb. Villa Sulay", aliases:["Villa Sulay"], route:"oriente", score:6},
  {name:"Urb. Rincon de las Margaritas", aliases:["Rincon de las Margaritas"], route:"por_asignar", score:50},
  {name:"Montemadero", route:"por_asignar", score:50},
  {name:"Urb. Ibagué 2000", aliases:["Ibagué 2000"], route:"por_asignar", score:50},
  {name:"Urb. la Ceiba Norte", aliases:["la Ceiba Norte"], route:"oriente", score:6},
  {name:"Urbanizacion los Ocobos", aliases:["los Ocobos"], route:"por_asignar", score:50},
  {name:"Monteverde del Vergel", route:"oriente", score:6},
  {name:"Urb. los Cambulos", aliases:["los Cambulos"], route:"occidente", score:5},
  {name:"Urb. la Candelaria", aliases:["la Candelaria"], route:"por_asignar", score:50},
  {name:"Villa Martha", route:"por_asignar", score:50},
  {name:"Urbanizacion Milenium I y II", aliases:["Milenium I y II"], route:"por_asignar", score:50},
  {name:"Palma del Vergel", route:"oriente", score:6},
  {name:"Urb. los Gualandayes", aliases:["los Gualandayes"], route:"por_asignar", score:50},
  {name:"Urb. la Floresta", aliases:["la Floresta"], route:"oriente", score:6},
  {name:"Villa Salome", route:"por_asignar", score:50},
  {name:"Urbanizacion Yacaira", aliases:["Yacaira"], route:"por_asignar", score:50},
  {name:"Paseo de San Francisco", route:"oriente", score:6},
  {name:"Urb. Villa Vanesa", aliases:["Villa Vanesa"], route:"por_asignar", score:50},
  {name:"Urb. la Victoria", aliases:["la Victoria"], route:"por_asignar", score:50},
  {name:"Villa Suiza", route:"por_asignar", score:50},
  {name:"Urbanizacion los Parrales", aliases:["los Parrales"], route:"por_asignar", score:50},
  {name:"Plazas del Bosque", route:"occidente", score:5},
  {name:"Villa Gloria", route:"por_asignar", score:50},
  {name:"Urb. Lady Di", aliases:["Lady Di"], route:"por_asignar", score:50},
  {name:"Atolsure", route:"por_asignar", score:50},
  {name:"Urb. Jardin Atolsure", aliases:["Jardin Atolsure"], route:"oriente", score:8},
  {name:"2 Etapa del Jordán", route:"oriente", score:6},
  {name:"Urb. los Remansos", aliases:["los Remansos"], route:"por_asignar", score:50},
  {name:"Arkalena", route:"occidente", score:10},
  {name:"12 de Octubre", route:"por_asignar", score:50},
  {name:"Andres Lopez de Galarza", route:"occidente", score:5},
  {name:"Albania", route:"por_asignar", score:50},
  {name:"Caminos del Bosque", route:"occidente", score:5},
  {name:"Urb. Jardin Av.", aliases:["Jardin Av."], route:"oriente", score:8},
  {name:"Alfonso Uribe Badillo", route:"occidente", score:5},
  {name:"Urb. Miraflores", aliases:["Miraflores"], route:"oriente", score:6},
  {name:"Bosques de Santa Helena", route:"occidente", score:5},
  {name:"Alto de la Cruz", route:"por_asignar", score:50},
  {name:"Avenida", route:"occidente", score:5},
  {name:"Boqueron", route:"occidente", score:10},
  {name:"Ciudadela Simon Bolivar I", route:"oriente", score:6},
  {name:"Urb. Jardin Chipalo", aliases:["Jardin Chipalo"], route:"oriente", score:8},
  {name:"Altamira", route:"por_asignar", score:50},
  {name:"Urb. Nuevo Horizonte", aliases:["Nuevo Horizonte"], route:"por_asignar", score:50},
  {name:"Boyaca", route:"occidente", score:5},
  {name:"America", route:"occidente", score:5},
  {name:"Colonias de Asprovi", route:"occidente", score:5},
  {name:"Cerro Granate", route:"occidente", score:10},
  {name:"Ciudadela Simon Bolivar II", route:"oriente", score:6},
  {name:"Urb. Jardin Chipalo II", aliases:["Jardin Chipalo II"], route:"oriente", score:8},
  {name:"Aparco", route:"oriente", score:10},
  {name:"Urb. Portal Campestre", aliases:["Portal Campestre"], route:"oriente", score:6},
  {name:"Cadiz", route:"occidente", score:5},
  {name:"Arado", route:"occidente", score:5},
  {name:"Galan", route:"occidente", score:5},
  {name:"Colina 1", route:"occidente", score:10},
  {name:"Ciudadela Simon Bolivar III", route:"oriente", score:6},
  {name:"Urb. Jardin II", aliases:["Jardin II"], route:"oriente", score:8},
  {name:"Arboleda", route:"por_asignar", score:50},
  {name:"Urb. Praderas de Santa Rita", aliases:["Praderas de Santa Rita"], route:"oriente", score:10},
  {name:"Casa Club", route:"occidente", score:5},
  {name:"Bosque Parte Alta", route:"occidente", score:5},
  {name:"Industrial", route:"occidente", score:5},
  {name:"Colina 2", route:"occidente", score:10},
  {name:"Conj. Residencial San Joaquin", aliases:["Residencial San Joaquin"], route:"por_asignar", score:50},
  {name:"Urb. Jardin Porvenir", aliases:["Jardin Porvenir"], route:"oriente", score:8},
  {name:"Arkaniza I", route:"oriente", score:6},
  {name:"Urb. Tahiti", aliases:["Tahiti"], route:"por_asignar", score:50},
  {name:"Castellana", route:"occidente", score:5},
  {name:"Bosque Parte Baja", route:"occidente", score:5},
  {name:"Keneddy", route:"occidente", score:5},
  {name:"Dario Echandia", route:"por_asignar", score:50},
  {name:"El Bunde I, II y III", route:"oriente", score:6},
  {name:"Urb. Jardin VI", aliases:["Jardin VI"], route:"oriente", score:8},
  {name:"Arkaniza II", route:"oriente", score:6},
  {name:"Urb. Varsovia", aliases:["Varsovia"], route:"por_asignar", score:50},
  {name:"Claret", route:"occidente", score:5},
  {name:"El Refugio II", route:"occidente", score:5},
  {name:"La Gaitana", route:"occidente", score:5},
  {name:"Granada", route:"occidente", score:10},
  {name:"El Bunde IV", route:"oriente", score:6},
  {name:"Urb. Jardines del Campo", aliases:["Jardines del Campo"], route:"oriente", score:8},
  {name:"Arkaparaiso", route:"oriente", score:6},
  {name:"Urb. Villa Arkadia", aliases:["Villa Arkadia"], route:"por_asignar", score:50},
  {name:"Departamental", route:"occidente", score:5},
  {name:"El Refugio I", route:"occidente", score:5},
  {name:"Isla", route:"occidente", score:5},
  {name:"German Huertas", route:"por_asignar", score:50},
  {name:"Urb. la Esmeralda", aliases:["la Esmeralda"], route:"por_asignar", score:50},
  {name:"Bello Horizonte", route:"por_asignar", score:50},
  {name:"Urb. Villa Cafe", aliases:["Villa Cafe"], route:"por_asignar", score:50},
  {name:"Federico Lleras", route:"occidente", score:5},
  {name:"Garzon", route:"occidente", score:5},
  {name:"La Pradera", route:"occidente", score:10},
  {name:"Jazmin", route:"por_asignar", score:50},
  {name:"Jardin I", route:"oriente", score:8},
  {name:"Urb. las Acacias", aliases:["las Acacias"], route:"por_asignar", score:50},
  {name:"Bosque de la Alameda", route:"occidente", score:5},
  {name:"Urb. Villa de la Candelaria", aliases:["Villa de la Candelaria"], route:"por_asignar", score:50},
  {name:"Hipodromo", route:"occidente", score:5},
  {name:"Independiente", route:"por_asignar", score:50},
  {name:"La Reforma", route:"occidente", score:10},
  {name:"La Union", route:"por_asignar", score:50},
  {name:"Jardin III", route:"oriente", score:8},
  {name:"Urb. los Comuneros", aliases:["los Comuneros"], route:"por_asignar", score:50},
  {name:"Carrenales", route:"por_asignar", score:50},
  {name:"Urb. Villa Luz", aliases:["Villa Luz"], route:"por_asignar", score:50},
  {name:"La Francia", route:"occidente", score:5},
  {name:"La Isla", route:"occidente", score:5},
  {name:"Las Vegas", route:"por_asignar", score:50},
  {name:"Miramar", route:"occidente", score:10},
  {name:"Jardin Parte Baja", route:"oriente", score:8},
  {name:"Urb. los Laureles", aliases:["los Laureles"], route:"occidente", score:5},
  {name:"Cond. las Palmeras", aliases:["las Palmeras"], route:"por_asignar", score:50},
  {name:"Urb. Villa Yuli", aliases:["Villa Yuli"], route:"por_asignar", score:50},
  {name:"Las Palmas", route:"occidente", score:5},
  {name:"La Martinica", route:"occidente", score:5},
  {name:"Matallana", route:"occidente", score:5},
  {name:"San Isidro", route:"por_asignar", score:50},
  {name:"Jardin Santander I, II y III", route:"oriente", score:8},
  {name:"Urb. los Pinos", aliases:["los Pinos"], route:"por_asignar", score:50},
  {name:"Conj. Residencial Valparaiso", aliases:["Residencial Valparaiso"], route:"occidente", score:5},
  {name:"Valparaiso I", route:"occidente", score:5},
  {name:"Laureles", route:"occidente", score:5},
  {name:"Las Brisas", route:"por_asignar", score:50},
  {name:"Murillo Toro", route:"occidente", score:5},
  {name:"Terrazas de Boqueron", route:"occidente", score:10},
  {name:"Jardin Valparaiso", route:"oriente", score:8},
  {name:"Urb. Nueva Castilla", aliases:["Nueva Castilla"], route:"occidente", score:5},
  {name:"El Tunal", route:"por_asignar", score:50},
  {name:"Valparaiso II", route:"occidente", score:5},
  {name:"Macarena Parte Alta", route:"occidente", score:5},
  {name:"Las Ferias", route:"occidente", score:5},
  {name:"Ricaurte", route:"occidente", score:10},
  {name:"Villa Mery", route:"occidente", score:10},
  {name:"La Cima I", route:"por_asignar", score:50},
  {name:"Urb. Nueva Colombia", aliases:["Nueva Colombia"], route:"por_asignar", score:50},
  {name:"Hacienda Piedra Pintada", route:"oriente", score:6},
  {name:"Valparaiso III", route:"occidente", score:5},
  {name:"Libertad", route:"occidente", score:5},
  {name:"Rosa Badillo", route:"occidente", score:5},
  {name:"La Cima II", route:"por_asignar", score:50},
  {name:"Urb. Nuevo Armero", aliases:["Nuevo Armero"], route:"por_asignar", score:50},
  {name:"Jordán 3 Etapa", aliases:["Jordan 3"], route:"oriente", score:6},
  {name:"Valparaiso IV", route:"occidente", score:5},
  {name:"Macarena Parte Baja", route:"occidente", score:5},
  {name:"Los Martires", route:"occidente", score:5},
  {name:"Santofimio", route:"occidente", score:10},
  {name:"Musicalia", route:"por_asignar", score:50},
  {name:"Urb. Nuevo Combeima", aliases:["Nuevo Combeima"], route:"occidente", score:5},
  {name:"Jordán I Etapa", aliases:["Jordan 1", "Jordán Primera Etapa"], route:"oriente", score:6},
  {name:"Versalles", route:"por_asignar", score:50},
  {name:"Magisterio", route:"occidente", score:5},
  {name:"Peñón", route:"occidente", score:5},
  {name:"Urb. Arkaima", aliases:["Arkaima"], route:"oriente", score:6},
  {name:"Palermo", route:"por_asignar", score:50},
  {name:"La Floresta", route:"oriente", score:6},
  {name:"Villa Carvajalita", route:"por_asignar", score:50},
  {name:"Metaima Alta", route:"occidente", score:5},
  {name:"Popular", route:"occidente", score:5},
  {name:"Urb. Divino Niño", aliases:["Divino Niño"], route:"por_asignar", score:50},
  {name:"Portal del Jardin", route:"oriente", score:8},
  {name:"Urb. Portal de Arkala", aliases:["Portal de Arkala"], route:"oriente", score:6},
  {name:"Los Tunjos", route:"por_asignar", score:50},
  {name:"Villa del Pilar", route:"por_asignar", score:50},
  {name:"Metaima Parte Baja", route:"occidente", score:5},
  {name:"Rodriguez Andrade", route:"por_asignar", score:50},
  {name:"Urb. Terrazas del Tejar", aliases:["Terrazas del Tejar"], route:"por_asignar", score:50},
  {name:"Reservas del Jardin", route:"oriente", score:8},
  {name:"Urb. Protecho", aliases:["Protecho"], route:"oriente", score:6},
  {name:"Picañelita", route:"oriente", score:10},
  {name:"Villa Maria", route:"occidente", score:5},
  {name:"Montealegre", route:"occidente", score:5},
  {name:"San Vicente de Paul", route:"occidente", score:5},
  {name:"Venecia", route:"occidente", score:10},
  {name:"Roberto Augusto Calderon", route:"por_asignar", score:50},
  {name:"Urb. Quinta Av.", aliases:["Quinta Av."], route:"por_asignar", score:50},
  {name:"Picaleña", aliases:["Cauchitos", "Aparco", "Guacán"], route:"oriente", score:10},
  {name:"Villa Natalia", route:"por_asignar", score:50},
  {name:"Nacional", route:"occidente", score:5},
  {name:"Uribe Uribe", route:"occidente", score:5},
  {name:"Villa Claudia", route:"por_asignar", score:50},
  {name:"San Gelato", route:"por_asignar", score:50},
  {name:"Urb. Tolima Grande", aliases:["Tolima Grande"], route:"oriente", score:6},
  {name:"Portal de los Tunjos", route:"por_asignar", score:50},
  {name:"Naciones Unidas", route:"occidente", score:5},
  {name:"Villa del Rio", route:"occidente", score:5},
  {name:"Villa Luces", route:"por_asignar", score:50},
  {name:"Topacio", aliases:["Jardín", "Jardín Santander"], route:"oriente", score:8},
  {name:"Urb. Vasconia", aliases:["Vasconia"], route:"oriente", score:8},
  {name:"Reservas del Campestre", route:"oriente", score:6},
  {name:"San Cayetano", route:"por_asignar", score:50},
  {name:"Yuldaima", route:"occidente", score:10},
  {name:"Tulio Varon", route:"por_asignar", score:50},
  {name:"Urb. Vasconia Reservado", aliases:["Vasconia Reservado"], route:"oriente", score:8},
  {name:"Rincon de las Americas", route:"oriente", score:6},
  {name:"Santa Helena", route:"por_asignar", score:50},
  {name:"Unidad Residencial Carabineros", aliases:["Carabineros"], route:"oriente", score:6},
  {name:"Urb. Villa del Norte", aliases:["Villa del Norte"], route:"oriente", score:6},
  {name:"Rincon del Campestre", route:"oriente", score:6},
  {name:"Santander", route:"occidente", score:5},
  {name:"Urb. 2 de Junio", aliases:["2 de Junio"], route:"por_asignar", score:50},
  {name:"Urb. Villa del Palmar", aliases:["Villa del Palmar"], route:"oriente", score:6},
  {name:"San Francisco", route:"oriente", score:6},
  {name:"Urb. Agua Marina", aliases:["Agua Marina"], route:"oriente", score:6},
  {name:"Urb. Villa del Sol", aliases:["Villa del Sol"], route:"oriente", score:6},
  {name:"San Remo", route:"por_asignar", score:50},
  {name:"Urb. Altos de Vasconia", aliases:["Altos de Vasconia"], route:"oriente", score:8},
  {name:"Urb. Villa Esperanza", aliases:["Villa Esperanza"], route:"oriente", score:6},
  {name:"Urb. Bosque de Varsovia", aliases:["Bosque de Varsovia"], route:"occidente", score:5},
  {name:"Urb. Antonio Maria", aliases:["Antonio Maria"], route:"por_asignar", score:50},
  {name:"Urb. Villa Jardin", aliases:["Villa Jardin"], route:"oriente", score:8},
  {name:"Urb. Chaquen", aliases:["Chaquen"], route:"por_asignar", score:50},
  {name:"Urb. Brisas de Vasconia", aliases:["Brisas de Vasconia"], route:"oriente", score:8},
  {name:"Urb. Villa la Paz", aliases:["Villa la Paz"], route:"oriente", score:6},
  {name:"Urb. Ciudad Luz", aliases:["Ciudad Luz"], route:"oriente", score:6},
  {name:"Urb. Buenaventura Garcia", aliases:["Buenaventura Garcia"], route:"por_asignar", score:50},
  {name:"Urb. Villa Magdalena", aliases:["Villa Magdalena"], route:"oriente", score:6},
  {name:"Urb. Confenalco", aliases:["Confenalco"], route:"oriente", score:6},
  {name:"Urb. Ciudad Blanca", aliases:["Ciudad Blanca"], route:"oriente", score:6},
  {name:"Urb. Villa Marcela", aliases:["Villa Marcela"], route:"oriente", score:6},
  {name:"Urb. Coopdiasam", aliases:["Coopdiasam"], route:"oriente", score:6},
  {name:"Urb. el Palmar I", aliases:["el Palmar I"], route:"oriente", score:6},
  {name:"Urb. Villa Vicentina", aliases:["Villa Vicentina"], route:"oriente", score:6},
  {name:"Urb. Cutucumay", aliases:["Cutucumay"], route:"oriente", score:6},
  {name:"Urb. el Palmar II", aliases:["el Palmar II"], route:"oriente", score:6},
  {name:"Villa Cristales", route:"por_asignar", score:50},
  {name:"Urb. el Poblado", aliases:["el Poblado"], route:"oriente", score:6},
  {name:"Urb. el Prado I", aliases:["el Prado I"], route:"oriente", score:6},
  {name:"Yerbabuena", route:"oriente", score:6},
  {name:"Urb. las Americas", aliases:["las Americas"], route:"oriente", score:6},
  {name:"Urb. el Prado II", aliases:["el Prado II"], route:"oriente", score:6},
  {name:"Urb. las Flores", aliases:["las Flores"], route:"oriente", score:6}
  ];
  window.AMARED_IBAGUE_NEIGHBORHOODS = AMARED_IBAGUE_NEIGHBORHOODS;
})();
